name: "[All-Purpose] Project Index"
description: 'Essential information for all DTS projects.'
title: 'Project: {{ inputs.project_name }}'
labels:
  - 'Project Index'
  - '[Service] :rotating_light: MISSING'
  - '[Type] :rotating_light: MISSING'
  - '[Workgroup] :rotating_light: MISSING'
assignees: []
body:
  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: Enter the project name in Title Case.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise, jargon + acronym-free 1-2 sentence description of the project.
      value: |
        <!-- (This text appears on the "Projects" page of the DTS website, so it should be easy for anyone—a TPW staff person, a Council member, or a prospective DTS intern—to understand. You may follow one of these loose formulas:
        - We're (building/implementing/evaluating) an (enhancement/application/initiative) for (users/workgroup/department) so that (value/outcome/impact).
        - We're (collaborating with/supporting) (users/workgroup/department) to (value/outcome/impact).  -->
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Clarify the organizational/operational context of this work. You may also want to add references to the final section below.
    validations:
      required: false
  - type: textarea
    id: desired_outcomes
    attributes:
      label: Desired Outcomes
      description: Explain the impact this project can have. Beyond the deliverables themselves, what will be different when this work is complete? What metrics are we using to measure success?
    validations:
      required: false
  - type: textarea
    id: scope_deliverables
    attributes:
      label: Scope & Deliverables
      description: Clarify what we are delivering. What platform? What's in scope, and (importantly!) what isn't? Are there constraints or potential roadblocks/challenges?
    validations:
      required: false
  - type: textarea
    id: timeframe
    attributes:
      label: Timeframe
      description: When will this project start, and how long do we think it will take? Include caveats for more complex or unpredictable projects.
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: Compile helpful documents and links here for easy reference.
      value: |
        <!-- 
        - Drive folder where project materials are stored.
        - Login page to related applications
        - Miro board 
        - Zenhub Filter or Board
        -->
    validations:
      required: false
  - type: input
    id: requested_by
    attributes:
      label: Requested by
    validations:
      required: false
  - type: input
    id: executive_sponsor
    attributes:
      label: Executive sponsor
    validations:
      required: false
  - type: input
    id: date
    attributes:
      label: Date
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        <!-- Add a thumbnail image for the DTS website following these guidelines: https://atd-dts.gitbook.io/wiki/product-ops/index-issue-specifications#index-issue-images.
        If there are multiple images, the first will be used as the thumbnail. -->

        ---
        This Github issue represents an Austin Transportation and Public Works' [Data & Technology Services](https://austinmobility.io/) team project. Project status is documented regularly in the comments below.

        <!-- 
        Don't forget to: 
        - Add a new "Project:" label here: https://github.com/cityofaustin/atd-data-tech/labels. Use the hex code #3D3D3D. 
        - Add "Workgroup:" and "Type:" labels
        -->